"""update addressf 

Revision ID: 0013094a4c16
Revises: c5307b0bb9ab
Create Date: 2020-05-31 22:23:28.492064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0013094a4c16'
down_revision = 'c5307b0bb9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('uuid', mysql.VARCHAR(length=1024), nullable=True))
    # ### end Alembic commands ###
