"""update goods no =>code

Revision ID: 21fa30d33f20
Revises: 9a53a253ec23
Create Date: 2020-05-31 20:48:48.246935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21fa30d33f20'
down_revision = '9a53a253ec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_model', sa.Column('code', sa.String(length=45), nullable=True))
    op.drop_index('no', table_name='goods_model')
    op.create_unique_constraint(None, 'goods_model', ['code'])
    op.drop_column('goods_model', 'no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_model', sa.Column('no', mysql.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'goods_model', type_='unique')
    op.create_index('no', 'goods_model', ['no'], unique=True)
    op.drop_column('goods_model', 'code')
    # ### end Alembic commands ###
