"""update baseModel

Revision ID: 46b7ab94b37c
Revises: 7c2ecd98461a
Create Date: 2020-05-31 15:44:31.873705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b7ab94b37c'
down_revision = '7c2ecd98461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_category_table',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sku_table',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('address_table', sa.Column('city', sa.String(length=45), nullable=True))
    op.add_column('address_table', sa.Column('country', sa.String(length=45), nullable=True))
    op.add_column('address_table', sa.Column('province', sa.String(length=45), nullable=True))
    op.add_column('address_table', sa.Column('street', sa.String(length=500), nullable=True))
    op.add_column('address_table', sa.Column('zip', sa.String(length=20), nullable=True))
    op.add_column('customer_table', sa.Column('name', sa.String(length=16), nullable=True))
    op.add_column('user_table', sa.Column('gender', sa.Boolean(), nullable=True))
    op.add_column('user_table', sa.Column('mobile', sa.Integer(), nullable=True))
    op.add_column('user_table', sa.Column('password', sa.String(length=45), nullable=False))
    op.add_column('user_table', sa.Column('username', sa.String(length=45), nullable=False))
    op.create_unique_constraint(None, 'user_table', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_column('user_table', 'username')
    op.drop_column('user_table', 'password')
    op.drop_column('user_table', 'mobile')
    op.drop_column('user_table', 'gender')
    op.drop_column('customer_table', 'name')
    op.drop_column('address_table', 'zip')
    op.drop_column('address_table', 'street')
    op.drop_column('address_table', 'province')
    op.drop_column('address_table', 'country')
    op.drop_column('address_table', 'city')
    op.drop_table('sku_table')
    op.drop_table('goods_category_table')
    # ### end Alembic commands ###
