"""update model

Revision ID: 9a53a253ec23
Revises: 46b7ab94b37c
Create Date: 2020-05-31 20:32:19.265374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a53a253ec23'
down_revision = '46b7ab94b37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_table', sa.Column('address', sa.String(length=512), nullable=True))
    op.add_column('address_table', sa.Column('area', sa.String(length=512), nullable=True))
    op.add_column('address_table', sa.Column('default_add', sa.Integer(), nullable=True))
    op.add_column('address_table', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('address_table', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('address_table', sa.Column('remarks', sa.String(length=512), nullable=True))
    op.add_column('goods_model', sa.Column('discount', sa.FLOAT(precision=32), nullable=True))
    op.add_column('goods_model', sa.Column('goods_info', sa.Text(), nullable=True))
    op.add_column('goods_model', sa.Column('image', sa.String(length=256), nullable=True))
    op.add_column('goods_model', sa.Column('old_price', sa.FLOAT(precision=16), nullable=True))
    op.add_column('goods_model', sa.Column('price', sa.FLOAT(precision=16), nullable=True))
    op.add_column('goods_model', sa.Column('sales', sa.Integer(), nullable=True))
    op.add_column('goods_model', sa.Column('share_link', sa.String(length=256), nullable=True))
    op.add_column('goods_model', sa.Column('skull_num', sa.Integer(), nullable=True))
    op.add_column('goods_model', sa.Column('start', sa.Integer(), nullable=True))
    op.add_column('goods_model', sa.Column('state', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'goods_model', ['image'])
    op.add_column('order_goods_table', sa.Column('num', sa.Integer(), nullable=True))
    op.add_column('order_goods_table', sa.Column('price', sa.String(length=32), nullable=True))
    op.add_column('order_table', sa.Column('alipay', sa.String(length=256), nullable=True))
    op.add_column('order_table', sa.Column('cancel', sa.Integer(), nullable=True))
    op.add_column('order_table', sa.Column('pay', sa.Integer(), nullable=True))
    op.add_column('order_table', sa.Column('pay_remark', sa.String(length=1024), nullable=True))
    op.add_column('order_table', sa.Column('remark', sa.String(length=512), nullable=True))
    op.add_column('order_table', sa.Column('times', sa.BIGINT(), nullable=True))
    op.add_column('user_table', sa.Column('ac_type', sa.String(length=4), nullable=True))
    op.add_column('user_table', sa.Column('account_atatus', sa.String(length=4), nullable=True))
    op.add_column('user_table', sa.Column('account_point', sa.Integer(), nullable=True))
    op.add_column('user_table', sa.Column('activate', sa.String(length=4), nullable=True))
    op.add_column('user_table', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column('user_table', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('user_table', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user_table', sa.Column('image', sa.TEXT(), nullable=True))
    op.add_column('user_table', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('user_table', sa.Column('member_grade', sa.String(length=4), nullable=True))
    op.add_column('user_table', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user_table', sa.Column('sex', sa.String(length=32), nullable=True))
    op.add_column('user_table', sa.Column('uuid', sa.String(length=1024), nullable=True))
    op.alter_column('user_table', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_index(op.f('ix_user_table_username'), 'user_table', ['username'], unique=True)
    op.drop_index('username', table_name='user_table')
    op.create_unique_constraint(None, 'user_table', ['password_hash'])
    op.create_unique_constraint(None, 'user_table', ['mobile'])
    op.drop_column('user_table', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('gender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_index('username', 'user_table', ['username'], unique=True)
    op.drop_index(op.f('ix_user_table_username'), table_name='user_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.alter_column('user_table', 'username',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('user_table', 'uuid')
    op.drop_column('user_table', 'sex')
    op.drop_column('user_table', 'password_hash')
    op.drop_column('user_table', 'member_grade')
    op.drop_column('user_table', 'info')
    op.drop_column('user_table', 'image')
    op.drop_column('user_table', 'email')
    op.drop_column('user_table', 'birthday')
    op.drop_column('user_table', 'avatar_hash')
    op.drop_column('user_table', 'activate')
    op.drop_column('user_table', 'account_point')
    op.drop_column('user_table', 'account_atatus')
    op.drop_column('user_table', 'ac_type')
    op.drop_column('order_table', 'times')
    op.drop_column('order_table', 'remark')
    op.drop_column('order_table', 'pay_remark')
    op.drop_column('order_table', 'pay')
    op.drop_column('order_table', 'cancel')
    op.drop_column('order_table', 'alipay')
    op.drop_column('order_goods_table', 'price')
    op.drop_column('order_goods_table', 'num')
    op.drop_constraint(None, 'goods_model', type_='unique')
    op.drop_column('goods_model', 'state')
    op.drop_column('goods_model', 'start')
    op.drop_column('goods_model', 'skull_num')
    op.drop_column('goods_model', 'share_link')
    op.drop_column('goods_model', 'sales')
    op.drop_column('goods_model', 'price')
    op.drop_column('goods_model', 'old_price')
    op.drop_column('goods_model', 'image')
    op.drop_column('goods_model', 'goods_info')
    op.drop_column('goods_model', 'discount')
    op.drop_column('address_table', 'remarks')
    op.drop_column('address_table', 'phone')
    op.drop_column('address_table', 'name')
    op.drop_column('address_table', 'default_add')
    op.drop_column('address_table', 'area')
    op.drop_column('address_table', 'address')
    # ### end Alembic commands ###
