"""update 

Revision ID: 9e9f6032c4e9
Revises: 21fa30d33f20
Create Date: 2020-05-31 21:57:06.149696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9f6032c4e9'
down_revision = '21fa30d33f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_table', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address_table', 'user_table', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address_table', type_='foreignkey')
    op.drop_column('address_table', 'users_id')
    # ### end Alembic commands ###
