"""updatefuck 

Revision ID: b2ac04c3a913
Revises: 9e9f6032c4e9
Create Date: 2020-05-31 22:01:10.552679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ac04c3a913'
down_revision = '9e9f6032c4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_table', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address_table', 'user_table', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address_table', type_='foreignkey')
    op.drop_column('address_table', 'users_id')
    # ### end Alembic commands ###
