"""update addressff 

Revision ID: ce964f59e5cb
Revises: 0013094a4c16
Create Date: 2020-05-31 22:25:57.797514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce964f59e5cb'
down_revision = '0013094a4c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('address_table_ibfk_1', 'address_table', type_='foreignkey')
    op.create_foreign_key(None, 'address_table', 'user_table', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address_table', type_='foreignkey')
    op.create_foreign_key('address_table_ibfk_1', 'address_table', 'address_table', ['users_id'], ['id'])
    # ### end Alembic commands ###
